blank_issues_enabled: true
contact_links:
  - name: â“ Support Question
    url: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
    about: If you have a question please see our docs or use our forums, helpdesk, or Slack community!
  - name: ğŸ“– Plugin documentation
    url: https://woocommerce.com/document/woocommerce-paypal-payments/
    about: Please review the documentation for guidance with the setup.
  - name: ğŸ‘¨â€ğŸ’» Developer documentation
    url: https://gist.github.com/InpsydeNiklas/b2dd0469eef25f8a89b8aaef5ff96c58?permalink_comment_id=4245135#gistcomment-4245135
    about: Tips to get started for developers interested in extending the pluging with modularity.
  - name: ğŸ”’ Security issue
    url: https://hackerone.com/automattic/
    about: For security reasons, please report all security issues via HackerOne. If the issue is valid, a bug bounty will be paid out to you. Please disclose responsibly and not via GitHub (which allows for exploiting issues in the wild before the patch is released).
